### ISSUE TITLE
buddy

### ISSUE THREAD

**Issue by SantaTrackerlol** [itztiva/Fortnitebuilds#2]
chapter 3 season 4 has archived builds

**Comment by itztiva** [comment]
send me it lol

**Comment by itztiva** [comment]
i dont put manifests builds on here, if you have a zip or rar to add then please put it

**Comment by SantaTrackerlol** [comment]
i have to upload it

**Comment by itztiva** [comment]
ok

**Comment by ByZNexus** [comment]
> i have to upload it

added as a torrent.
